### ISSUE TITLE
Cannot import instrument results using CSV

### ISSUE THREAD

**Issue by cpang2** [bikalabs/bika.lims#2037]
## Steps to reproduce
1. Log in to https://bikalims.ridingbytes.com
2. Create AR: H2O-0001-R01 and select analysis services
3. Change AR status to received
4. Create instrument file and make sure the analysis service keywords are included as column headers
5. Go to Import window, select FOSS - Winescan FT 120 from the dropdown
6. Attach the file and click on the Submit button
7. Import failed. Logs are found below.
8. Try using AR ID and get the same error. Screenshots and import file are attached in instrument.zip
[instrument.zip](https://github.com/bikalabs/bika.lims/files/1004105/instrument.zip)

Log trace

Parsing file FOSSWinescanFT120_test.csv
End of file reached successfully: 1 objects, 0 analyses, 1 results
Allowed Analysis Request states: sample_received
Allowed analysis states: sampled, sample_received, attachment_due, to_be_verified
Import finished successfully: 0 ARs and 0 results updated

Error
Errors

Service keywords: no matches found
No analyses 'sampled, sample_received, attachment_due, to_be_verified' states found for H2O-0001	1	Water	4.06	10	8	2010/11/02	10:33 AM
No Analysis Request with 'sample_received' states neither QC analyses found for H2O-0001	1	Water	4.06	10	8	2010/11/02	10:33 AM

## Current behavior
Results are not imported.

**Comment by rockfruit** [comment]
Hi,

The message `Service keywords: no matches found` indicates that no ARs containing Analyses derived from AnalysisServices having Keywords matching the column headers exist exist on the system.

In the example file at https://github.com/bikalabs/bika.lims/blob/master/bika/lims/exportimport/instruments/foss/winescan/samples/ft120.csv are the column headers which are the keywords required in these services.

So, you'll need to create or edit an analysis service, and set the keyword to one of these.  Then, create a new AR, and make sure that the relevant service is selected.  Then, if your input file's "Sample ID" column contains a value that matches the Sample ID, Request ID, or Client Sample ID of one of the existing ARs in the correct state, it's values should be completed.

Well the mess

**Comment by lemoene** [comment]
phew, now it appears completely broken, I must be doing something wrong. 

UnboundLocalError: local variable 'dateTime' referenced before assignment

I made sure the attached CSV was saved in UTF 8, but get the same error with various files, e.g. the attached, matching up with https://bikalims.ridingbytes.com/worksheets/WS-001/manage_results
[FOSS_WinescanFT120 test 170517 2.csv.zip](https://github.com/bikalabs/bika.lims/files/1009188/FOSS_WinescanFT120.test.170517.2.csv.zip)

Traceback (most recent call last):
  File "/home/bika/bikalims/src/bika.lims/bika/lims/exportimport/instruments/foss/winescan/ft120.py", line 76, in Import
    importer.process()
  File "/home/bika/bikalims/src/bika.lims/bika/lims/exportimport/instruments/resultsimport.py", line 327, in process
    self._parser.parse()
  File "/home/bika/bikalims/src/bika.lims/bika/lims/exportimport/instruments/resultsimport.py", line 224, in parse
    jump = self._parseline(line)
  File "/home/bika/bikalims/src/bika.lims/bika/lims/exportimport/instruments/foss/winescan/ft120.py", line 110, in _parseline
    return WinescanCSVParser._parseline(self, line)
  File "/home/bika/bikalims/src/bika.lims/bika/lims/exportimport/instruments/foss/winescan/__init__.py", line 89, in _parseline
    self._addRawResult(resid, outvals, True)
  File "/home/bika/bikalims/src/bika.lims/bika/lims/exportimport/instruments/foss/winescan/ft120.py", line 151, in _addRawResult
    values[keyword]['DateTime'] = dateTime
UnboundLocalError: local variable 'dateTime' referenced before assignment

**Comment by rockfruit** [comment]
OK  the PR above should fix this so that an error is raised, which shows some meaning about what's going wrong with your file in this case

**Comment by lemoene** [comment]
oh dear, now she does not like the date format:
**: time data '2010/11/02 10:33 AM' does not match format '%d/%m/%Y %H:%M %p'**

I am continuing sans dates to get to the root of Cecily's original issue

Traceback (most recent call last):
  File "/home/bika/bikalims/src/bika.lims/bika/lims/exportimport/instruments/foss/winescan/ft120.py", line 77, in Import
    importer.process()
  File "/home/bika/bikalims/src/bika.lims/bika/lims/exportimport/instruments/resultsimport.py", line 327, in process
    self._parser.parse()
  File "/home/bika/bikalims/src/bika.lims/bika/lims/exportimport/instruments/resultsimport.py", line 224, in parse
    jump = self._parseline(line)
  File "/home/bika/bikalims/src/bika.lims/bika/lims/exportimport/instruments/foss/winescan/ft120.py", line 109, in _parseline
    return WinescanCSVParser._parseline(self, line)
  File "/home/bika/bikalims/src/bika.lims/bika/lims/exportimport/instruments/foss/winescan/__init__.py", line 89, in _parseline
    self._addRawResult(resid, outvals, True)
  File "/home/bika/bikalims/src/bika.lims/bika/lims/exportimport/instruments/foss/winescan/ft120.py", line 139, in _addRawResult
    dtobj = datetime.strptime(dtstr, '%d/%m/%Y %H:%M %p')
  File "/usr/lib/python2.7/_strptime.py", line 332, in _strptime
    (data_string, format))
ValueError: time data '2010/11/02 10:33 AM' does not match format '%d/%m/%Y %H:%M %p'

**Comment by cpang2** [comment]
I tried modifying the date format from 2010/11/02 to 02/11/2010 and now seeing another error

Perhaps I didn’t pick the good example (winescan ft120) for testing? My original intention is to test the instrument/result import process. If this instrument interface is no longer supported I can test another one but would need some guidance on finding the good sample file.

Traceback (most recent call last):
  File "/home/bika/bikalims/src/bika.lims/bika/lims/exportimport/instruments/foss/winescan/ft120.py", line 77, in Import
    importer.process()
  File "/home/bika/bikalims/src/bika.lims/bika/lims/exportimport/instruments/resultsimport.py", line 327, in process
    self._parser.parse()
  File "/home/bika/bikalims/src/bika.lims/bika/lims/exportimport/instruments/resultsimport.py", line 224, in parse
    jump = self._parseline(line)
  File "/home/bika/bikalims/src/bika.lims/bika/lims/exportimport/instruments/foss/winescan/ft120.py", line 109, in _parseline
    return WinescanCSVParser._parseline(self, line)
  File "/home/bika/bikalims/src/bika.lims/bika/lims/exportimport/instruments/foss/winescan/__init__.py", line 89, in _parseline
    self._addRawResult(resid, outvals, True)
  File "/home/bika/bikalims/src/bika.lims/bika/lims/exportimport/instruments/foss/winescan/ft120.py", line 156, in _addRawResult
    row, rows = self._extractrowbycalibration(rows, self._calibration)
TypeError: _extractrowbycalibration() takes exactly 3 arguments (2 given)

**Comment by lemoene** [comment]
now using Cecily's file with the date fixed - **NB, this should be done in the code**

**TypeError: _extractrowbycalibration() takes exactly 3 arguments (2 given)**

Traceback (most recent call last):
  File "/home/bika/bikalims/src/bika.lims/bika/lims/exportimport/instruments/foss/winescan/ft120.py", line 77, in Import
    importer.process()
  File "/home/bika/bikalims/src/bika.lims/bika/lims/exportimport/instruments/resultsimport.py", line 327, in process
    self._parser.parse()
  File "/home/bika/bikalims/src/bika.lims/bika/lims/exportimport/instruments/resultsimport.py", line 224, in parse
    jump = self._parseline(line)
  File "/home/bika/bikalims/src/bika.lims/bika/lims/exportimport/instruments/foss/winescan/ft120.py", line 109, in _parseline
    return WinescanCSVParser._parseline(self, line)
  File "/home/bika/bikalims/src/bika.lims/bika/lims/exportimport/instruments/foss/winescan/__init__.py", line 89, in _parseline
    self._addRawResult(resid, outvals, True)
  File "/home/bika/bikalims/src/bika.lims/bika/lims/exportimport/instruments/foss/winescan/ft120.py", line 156, in _addRawResult
    row, rows = self._extractrowbycalibration(rows, self._calibration)
TypeError: _extractrowbycalibration() takes exactly 3 arguments (2 given)

**Comment by lemoene** [comment]
Continuing test with WineScan Auto

**Comment by lemoene** [comment]
Winescan auto works perfectly, even with deliberate error in file - correctly picked up, _Service keyword GluFruc not found_

**Comment by lemoene** [comment]
I don't think this bug should hold back the release, the instrument is only used in the Wine industry and we do not have any Wine clients at the moment. FT120 has been replaced by the WineScan Auto in any case. Any FT120's out there will be more than 10 years old

I saw Alex Limi admit the other day that while he was with Mozilla, they shipped a version of FF with several dead serious bugs in some dusty corners (to millions of users).

Not the way we work Cecily, but nobody (as usual) is paying for this.

(I mailed Cecily the Winescan Auto files privately) Does not seem one can assign priorities in this tracker..., but imho this should go right down to the bottom of the stack. Hell we have more important stuff to do!

**Comment by cpang2** [comment]
Tried winescan auto and that one works perfectly. Sorry for picking the bad example for testing.

If it’s no longer used, there is no need for fixing it.

Maybe someone can update this link so other newbies like me will not test using an old example?

https://github.com/bikalabs/bika.lims/wiki/Results-import-from-spreadsheet

Thanks for everyone’s help (as always). Really appreciated.

Thanks,
Cecily
