### ISSUE TITLE
Infinite Recursion on Report Publication

### ISSUE THREAD

**Issue by ramonski** [bikalabs/bika.lims#2128]
## Steps to reproduce

- Create a new client w/o any address details.
- Add a contact w/o any address details
- Create a new AR and publish the results

## Current behavior

Maximum recursion error

## Expected behavior

Report renders

## Screenshot (optional)

```
Traceback (most recent call last):
  File "/home/bika/bikalims/src/bika.lims/bika/lims/browser/analysisrequest/publish.py", line 215, in getGroupedReportTemplate
    embedt, reptemplate = self._renderTemplate()
  File "/home/bika/bikalims/src/bika.lims/bika/lims/browser/analysisrequest/publish.py", line 189, in _renderTemplate
    return embedt, embed(self)
  File "/home/bika/buildout-cache/eggs/Zope2-2.13.26-py2.7.egg/Products/Five/browser/pagetemplatefile.py", line 59, in __call__
    sourceAnnotations=getattr(debug_flags, 'sourceAnnotations', 0),
  File "/home/bika/buildout-cache/eggs/zope.pagetemplate-3.6.3-py2.7.egg/zope/pagetemplate/pagetemplate.py", line 132, in pt_render
    strictinsert=0, sourceAnnotations=sourceAnnotations
  File "/home/bika/buildout-cache/eggs/five.pt-2.2.4-py2.7.egg/five/pt/engine.py", line 98, in __call__
    return self.template.render(**kwargs)
  File "/home/bika/buildout-cache/eggs/z3c.pt-3.0-py2.7.egg/z3c/pt/pagetemplate.py", line 163, in render
    return base_renderer(**context)
  File "/home/bika/buildout-cache/eggs/Chameleon-2.25-py2.7.egg/chameleon/zpt/template.py", line 261, in render
    return super(PageTemplate, self).render(**vars)
  File "/home/bika/buildout-cache/eggs/Chameleon-2.25-py2.7.egg/chameleon/template.py", line 191, in render
    raise_with_traceback(exc, tb)
  File "/home/bika/buildout-cache/eggs/Chameleon-2.25-py2.7.egg/chameleon/template.py", line 171, in render
    self._render(stream, econtext, rcontext)
  File "d3fb32d28ddde6f4f8ae89a28ed0bbff.py", line 165, in render
  File "/home/bika/bikalims/src/bika.lims/bika/lims/browser/analysisrequest/publish.py", line 153, in getAnalysisRequest
    else self._ar_data(self._ars[self._current_ar_index])
  File "/home/bika/bikalims/src/bika.lims/bika/lims/browser/analysisrequest/publish.py", line 351, in _ar_data
    data['client'] = self._client_data(ar)
  File "/home/bika/bikalims/src/bika.lims/bika/lims/browser/analysisrequest/publish.py", line 626, in _client_data
    data['address'] = to_utf8(self._client_address(client))
  File "/home/bika/bikalims/src/bika.lims/bika/lims/browser/analysisrequest/publish.py", line 608, in _client_address
    contact = self.getAnalysisRequest().getContact()
  File "/home/bika/bikalims/src/bika.lims/bika/lims/browser/analysisrequest/publish.py", line 153, in getAnalysisRequest
    else self._ar_data(self._ars[self._current_ar_index])
  File "/home/bika/bikalims/src/bika.lims/bika/lims/browser/analysisrequest/publish.py", line 351, in _ar_data
    data['client'] = self._client_data(ar)
  File "/home/bika/bikalims/src/bika.lims/bika/lims/browser/analysisrequest/publish.py", line 626, in _client_data
    data['address'] = to_utf8(self._client_address(client))
  File "/home/bika/bikalims/src/bika.lims/bika/lims/browser/analysisrequest/publish.py", line 608, in _client_address
    contact = self.getAnalysisRequest().getContact()
  File "/home/bika/bikalims/src/bika.lims/bika/lims/browser/analysisrequest/publish.py", line 153, in getAnalysisRequest

[...]

RuntimeError: maximum recursion depth exceeded

 - Expression: "python:view.getAnalysisRequest()"
 - Filename:   ... ms/browser/reports/default.pt
 - Location:   (line 20: col 32)
 - Source:     ... "analysisrequest python:view.getAnalysisRequest();
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 - Arguments:  repeat: {...} (0)
               template: 
               views: 
               modules: 
               args: 
               here: 
               user: 
               nothing: 
               container: 
               request: 
               wrapped_repeat: 
               traverse_subpath: 
               default: 
               loop: {...} (0)
               context: 
               view: 
               translate: 
               root: 
               options: {...} (0)
               target_language: 
```

**Comment by ramonski** [comment]
The issue is here:

https://github.com/bikalabs/bika.lims/blob/master/bika/lims/browser/analysisrequest/publish.py#L608

`self.getAnalysisRequest()` does **not** return the current context, but executes again the whole data collection machinery of the `publish` module itself.
